<?php
/**
 * @file
 * A module to make an AJAX call to an external rbemail server.
 */

 function rbemail_preprocess_page(&$variables) {
   drupal_add_js(array('rbemail' => array(
     'formID' => '#webform-client-form-21',
     'successText' => 'Thank you, someone will be in touch with you shortly.',
     'valError1' => 'This field is required.',
     'valError2' => 'This is not the correct format for this field.'
     )), 'setting');
   drupal_add_js(drupal_get_path('module','rbemail') . '/js/validate.js');
 }

 function rbemail_form_webform_client_form_21_alter(&$form, &$form_state, $form_id) {
   $form['#action'] = 'http://localhost:9393';
 }
