<?php
/**
 * @file
 * A module to make an AJAX call to an external rbemail server.
 */

 function rbemail_preprocess_page(&$variables) {
     drupal_add_js(drupal_get_path('module','rbemail') . '/js/validate.js');
     $variables['scripts'] = drupal_get_js();
 }

 function rbemail_form_webform_client_form_21_alter(&$form, &$form_state, $form_id) {
   $form['#action'] = 'http://localhost:9393';
 }
